framework:
    notifier:
        chatter_transports:
#            fakechat+logger: '%env(FAKE_CHAT_DSN)%'
            telegram: '%env(TELEGRAM_DSN)%'
#        texter_transports:
#            fakesms+email: '%env(FAKE_SMS_DSN)%'
#        admin_recipients:
#            - { email: admin@example.com }
